spring:
  datasource:
    url: ${MATCH_DB_URL}
    username: ${MATCH_DB_USERNAME}
    password: ${MATCH_DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

server:
  port: ${MATCH_DB_PORT}
  error:
    include-message: always

